backend:
  name: git-gateway
  branch: master
media_folder: "img/uploads"
site_url: https://madrizbio.netlify.com
display_url: https://madrizbio.netlify.com
logo_url: "/img/mabdi_logo.png"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: directorio
    label: Tiendas
    folder: "colecciones/_directorio"
    create: true
    slug: "{{slug}}"
    media_folder: "img/card-tiendas"
    fields:
      - {label: "Nombre de la tienda", name: "title", widget: "string"}
      - {label: "Región", name: "region", widget: "string"}
      - {label: "Página web", name: "web", widget: "string", required: false}
      - {label: "Dirección", name: "address", widget: "string"}
      - {label: "Teléfono", name: "phone", widget: "string"}
      - {label: "Imagen de la tienda", name: "img_path", widget: "image", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}
  - name: "objetivos"
    label: Objetivos de MadrizBio
    folder: "colecciones/_objetivos"
    create: false
    fields:
      - {label: "Objetivo", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "hidden"}
      - {label: "Descripción objetivo", name: "body", widget: "markdown"}
  - name: "oferta"
    label: Oferta de MadrizBio
    folder: "colecciones/_oferta"
    create: false
    fields:
      - {label: "Título oferta", name: "title", widget: "string"}
      - {label: "Imagen Oferta", name: "img_path", widget: "image"}
      - {label: "Descripción oferta", name: "body", widget: "markdown"}
  - name: "unirse"
    label: Razones para unirse a MadrizBio
    folder: "colecciones/_unirse"
    create: false
    fields:
      - {label: "Título razón", name: "title", widget: "string"}
      - {label: "Imagen razón", name: "img_path", widget: "image"}
      - {label: "Argumento", name: "body", widget: "markdown"}
  - name: "regiones"
    label: Regiones
    folder: "colecciones/_regiones"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre de la región", name: "title", widget: "string"}